### ISSUE TITLE
Seafarer's Doubloons count incorrect.

### ISSUE THREAD

**Issue by Sinaloit** [Xruptor/BagSync#85] opened 2020-01-19 22:02 UTC
Seafarer's Doubloons appear to only be listing the leftmost digit in the character tooltip.  Example I have  296 but the tooltip indicates the character has 2.  I also do not see Seafarer's Doubloons at all in the BagSync - Currency window.

**Comment by Xruptor** [comment] 2020-01-20 13:09
I'll take a look at this and see if I can reproduce the error.  It may be an issue with how the itemid/itemlink is done with this particular item.

**Comment by Xruptor** [comment] 2020-01-20 15:28
I was under the impression that Doubloons don't go into your inventory but to your currency window instead.  So the tooltip is only shown for them when you hover over it in the currency window.  I'm assuming what you are saying is that the display is both in the official currency window and in the BagSync currency display?  Could you provide a screenshot?  I will try to replicate this when I get home.

**Comment by Sinaloit** [comment] 2020-01-20 19:46
Yes, Doubloons do not go into inventory so yes you are correct the tooltip I am referring to is from the currency window.
![image](https://user-images.githubusercontent.com/63269/72753660-56691e80-3b7a-11ea-85a8-47575f6ecca7.png)

The BagSync - Currency window that does not show them at all is this one:
![image](https://user-images.githubusercontent.com/63269/72753696-73055680-3b7a-11ea-8bc4-b84246829991.png)

**Comment by schrottbrennt** [comment] 2020-01-20 19:47
I'll provide a screenshot as well, sorry it's in German. Seafarer as well as Corrupted Memento and Brawlers Gold seem to be buggy or there is a problem with the database in general. 
The screen shows my character having 523 dubloons, but the BagSync tooltip says 6 (for all chars by the way). For Corrupted Memento I have 398, tooltip says 0.
![WoWScrnShot_012020_203843](https://user-images.githubusercontent.com/60113648/72753625-ae794280-3bc5-11ea-9eaa-c084e97b1044.jpg)

**Comment by Sinaloit** [comment] 2020-01-20 19:51
Oddly my corrupted mementos tooltip appears to be correct.  I'm guessing brawlers gold is correct but I haven't participated in the current season yet so am unsure if anything would change.

**Comment by Xruptor** [comment] 2020-01-20 21:05
After looking at those screenshots, I suspect the issue is something related to localization and itemID storing.

So lets take a look at how things are being stored.

Please send me a PM (Private Message) on WOWInterface or wow.curse.com
In that message, if you could please attach or include in a zip file your BagSync.lua savedvariables.

You can find it in the following location  C:\YOUR WOW INSTALL DIR\_retail\WTF\YOUR ACCOUNT NAME\SavedVariables\BagSync.lua

I can use that file to determine how things are being stored and interpreted on your end.  It may help me solve the issue.

**Comment by Xruptor** [comment] 2020-01-20 21:36
That GitGist helped tremendously.  I found the culprit!

Looks like multiple currency is sharing the same iconID but have a different currencyID.  Figures that Blizzard would do this.  Their code can be sloppy sometimes.

So doubloons are listed as 1604167.  But if you notice Seal of Broken Fate are also 1604167.  That is why it is only showing you such tiny numbers.  It's overwriting the doubloons.  This is a major issue.  

I'll need to code a way around this.  I'll be working on a fix.

**Comment by Xruptor** [comment] 2020-01-21 12:51
Issue has been fixed in the latest commit above.  Will be released with next version push.

**Closed by Xruptor** 2020-01-21 12:51 UTC
Labels: Bug
