### ISSUE TITLE
screenfreeze

### ISSUE THREAD

**Issue by anotherone20** [Xruptor/BagSync#83] opened 2020-01-18 08:56 UTC
since last update which made it to work in 8.3 when hovering over any item screen freezes for some secs (like for collecting data)

**Comment by Xruptor** [comment] 2020-01-18 13:35
Did you have this issue before 8.3?  Were you using BagSync fine for a period of time?  The addon has been completely rewritten so I may need to sort out issues.

Is your computer really REALLY old or brand new?  (This is a question related to processing cycles so I have a general idea on performance.)  How many characters do you have and how many accounts do you have?  How old is your account and do you have lots of items?  Are you in a guild?

I can work with you to solve this issue, but we need to track down why you are getting this slow freezing issue.

**Comment by anotherone20** [comment] 2020-01-18 18:01
hi! no problem before 8.3 (and it wasn't working between 8.3 release and last update) i think this has already happened some time ago after a patch. anyway yes my pc is old (maybe really lol), it still happens with all addons disabled but BagSync.
I've got a dozen of chars I'm using it on with guild banks pretty much empty.

**Comment by Xruptor** [comment] 2020-01-18 21:09
Exit WOW first.

Try this and see if it helps.  Go to your WOW installation directory. Go to _retail   Go to your WTF folder, then Accounts, then your ACCOUNT name folder.  Then under SavedVariables delete anything you see that has BagSync in the name. 

Now startup WOW and see if that has made a difference on your characters.  If not then I'll implement some minor patches for you to test to see if that helps you.

**Comment by anotherone20** [comment] 2020-01-18 21:13
Thanks I will try it later when I get to pc

**Comment by anotherone20** [comment] 2020-01-18 22:58
here I am. looks like it fixed it!

**Comment by anotherone20** [comment] 2020-01-21 19:50
aaand it has happened again... I cleared those files and everything went fine again but now it freezes again when I over items :((

**Comment by Xruptor** [comment] 2020-01-21 20:04
Go to your WOW Installation folder.  Under c:\YOUR WOW FOLDER\_retail\WTF\YOUR ACCOUNT
go to your SavedVariables folder within that account.  Find BagSync.lua.  

I need you to send me that file as a Private Message on either WOWInterface.com or WOW.Curse.com

You can use
https://gist.github.com/

If you want to copy and paste and create a SECRET link for me to view the data.  Or you can zip it up and figure a way to upload it.  Do not post it here though.

**Comment by anotherone20** [comment] 2020-01-21 22:37
sent

**Comment by Xruptor** [comment] 2020-01-22 00:18
> sent

I got the file thanks.  I'll review it and see if I notice anything.

**Comment by Xruptor** [comment] 2020-01-22 00:30
Okay I'm seeing a LUDICROUS amount of BattlePet data in your BagSync DB.  Do you have many Battle Pets on multiple characters and on the auction house?  I'm seeing quite literally hundreds of them.  A lot of them with the exact same name.

**Comment by anotherone20** [comment] 2020-01-22 00:36
haha i do have many battle pets in my journal but a dozen on the ah

**Comment by anotherone20** [comment] 2020-01-22 00:44
maybe it bugs out with tradeskillmaster addon data?

**Comment by Xruptor** [comment] 2020-01-22 01:06
No I think it's the Battle Pets for sure.  You have many MANY of them that are repeating.  It's saying you have 95,745 battle pets.  That can't be right.  Please do a count for each battle pet you have in your bags and in the auction house for each character.  Then post it here.  I need something to compare this DB with.

Something like this.  With the location and the number of battle pets in that location.  You don't have to do all the characters.  I just need a general idea of how many Battle Pets you actually have.

Character A
Bags -10
Bank - 5
Auction - 20

Character B
Bags - 2
Bank - 10
Auction - 40

**Comment by anotherone20** [comment] 2020-01-22 01:07
yeah it's not right... it is like literally those 10-15 pets are duplicated for ever on evey character

**Comment by anotherone20** [comment] 2020-01-22 01:18
k will do it asap

**Comment by anotherone20** [comment] 2020-01-22 01:49
I've got no duplicated pet and none in banks, just not 100% sure where they were when the file was written.

char1
AH - 16

char2
AH - 8

char3
AH - 2

no other chars have pets around

**Comment by Xruptor** [comment] 2020-01-22 03:55
Okay that helps.  Let me look at what I can do.  Obviously the auction house is storing the data more times then it should.  So I need to see why.  None of your characters have the battlepets in their bags or bank right?

**Comment by anotherone20** [comment] 2020-01-22 09:00
none in bank and I believe in the moment it logged none in bags either

**Comment by anotherone20** [comment] 2020-01-22 09:02
i see you published an update, gonna try it

**Comment by Xruptor** [comment] 2020-01-22 13:19
> none in bank and I believe in the moment it logged none in bags either
> edit:: I see you published an update so I'm making a clean installation

Yeah that update won't help you.  The issue is the battlepets  I'm working on that as we speak.

**Comment by anotherone20** [comment] 2020-01-22 13:52
you're awesome

**Comment by Sinaloit** [comment] 2020-01-22 21:18
I too am getting slowness the server shutdown before I was able to disable addons to verify that it was bagsync, but I perused my Bagsync.lua and one thing I noticed  is that there is a reagentbank and reagents section that appears to be the same for two of my characters.  How are those sections supposed to be different? Is reagentbank supposed to be deprecated?

**Comment by Xruptor** [comment] 2020-01-23 05:10
I've updated this to v12.3  please do a  /bgs resetdb
Monitor your SavedVariables for BagSync.lua and see that it's working as it should.  If you start getting duplicating entries please let me know.

**Comment by Sinaloit** [comment] 2020-01-23 07:01
BagSync\libs\LibQTip-1.0\LibQTip-1.0-38.lua:175: unexpected symbol near ']'
There appears to be 2 sets of ]===] at the end of  the debug section and lua apparently isn't liking that.  Removed the 2nd ]===] and it loaded without errors.

**Comment by anotherone20** [comment] 2020-01-23 09:14
Thanks!
> Monitor your SavedVariables for BagSync.lua and see that it's working as it should. If you start getting duplicating entries please let me know.
I can briefly tell it by just checking file size right?

**Comment by anotherone20** [comment] 2020-01-23 09:59
tooltips are not showing! even if the addon records thing because searching in bags works (just logged 2 chars so far so I'm sure)
can create a new ticket if you prefer

**Comment by anotherone20** [comment] 2020-01-23 15:18
tooltip is back! let the database be rebuild and see if there is any issue..

**Comment by anotherone20** [comment] 2020-01-23 19:32
I'm sorry but looks like is duplicating random stuff... lemme check better haha

**Comment by anotherone20** [comment] 2020-01-23 21:39
ok new update reset the database, for now it is ok but haven't logged all my characters

**Comment by Xruptor** [comment] 2020-01-23 23:06
If you are still getting the issue.  Make sure it's just the auction house data that is being affected.  If it's not and other data in your bags and such is being replicated.  Then I have no idea what could be causing that.  It's literally a from slot 1 to how every many slots you have in your bag or bank.  So it can't go from 1 to 9000 if you only have 50 slots in your bags.  

It could be possible it's another addon causing this issue.  IF you still have the problem.  Please post a list of the addons you use.

**Comment by Gnovas** [comment] 2020-01-24 04:11
I got the same screenfreeze problems, /bgs resetdb  works perfect, but it happened again, and I'd guess it is because of AH, when i open it the syn goes crazy saying i have 9000 of X item

**Comment by anotherone20** [comment] 2020-01-24 09:20
morning, I confirm it is happening again and the AH is involved: anything that pass trough it might get affected... not everything and looks like BOE or enchant aren't lol maybe things that I have on multiple characters if one post them the add on starts to duplicate. not sure if it might be another addon conflict I will try later. :((

**Comment by Xruptor** [comment] 2020-01-24 14:12
> I got the same screenfreeze problems, /bgs resetdb works perfect, but it happened again, and I'd guess it is because of AH, when i open it the syn goes crazy saying i have 9000 of X item

Can you please send me your SavedVariables for BagSync.lua? You can find it under C:\WOW_retail\WTF\YOUR ACCOUNT\SavedVariables\BagSync.lua.

Please use WOWInterface or Wow.curse.com to send me the message. My username is Xruptor.

Also can you write up the addons you are using?  It may be a common addon everyone is using that is causing this issue.



> morning, I confirm it is happening again and the AH is involved: anything that pass trough it might get affected... not everything and looks like BOE or enchant aren't lol maybe things that I have on multiple characters if one post them the add on starts to duplicate. not sure if it might be another addon conflict I will try later. :((

Can you write up the addons you are using?  It may be a common addon everyone is using that is causing this issue.

**Comment by Xruptor** [comment] 2020-01-24 15:31
I've just uploaded version 12.7. Please see if that fixes the issue for you.

**Comment by anotherone20** [comment] 2020-01-24 16:45
thanks. made a clean installation. logging in now since this morning. I'll play asap with AH.
among the others I was thinking about Postal addon for mailbox and TSM for AH (which has a function to track items too). If this happens again I'll try to play w/o them.

**Comment by Xruptor** [comment] 2020-01-25 00:36
I haven't heard back so I'm assuming it works fine now?

**Comment by anotherone20** [comment] 2020-01-25 10:16
Good morning! (at least here XD) I can say so far so good! I've logged all my chars yesterday and played all the AH I usually do and so far no duplicated items! was it the Ah then?

**Comment by Xruptor** [comment] 2020-01-25 12:10
> Good morning! (at least here XD) I can say so far so good! I've logged all my chars yesterday and played all the AH I usually do and so far no duplicated items! was it the Ah then?

It was a combination of two things.  A mistake on my part in the BagSync code and working around Blizzards buggy terrible new Auction Code.  I had to put measures in to prevent these things from happening.

Since everything checks out.  I'm going to close this issue.  Thanks everyone for your help.

**Closed by Xruptor** 2020-01-25 12:10 UTC
Labels: Bug
