### ISSUE TITLE
Lua Error

### ISSUE THREAD

**Issue by Galiwyx** [Xruptor/BagSync#67] opened 2018-07-18 11:28 UTC
This addon seems abandonned but since the release of 8.0.1 i Have a lua Error : 

`Message: Binding header BAGSYNC is defined more than once in Interface\AddOns\BagSync\Bindings.xml
Time: Wed Jul 18 13:15:07 2018
Count: 10`

thank you

**Comment by soulyouth** [comment] 2018-07-21 11:36
edit bindings.xml and change it to this 
<Bindings>
   <Binding name="BAGSYNCBLACKLIST" header="BAGSYNC1" category="ADDONS">
    BagSync_ShowWindow("Blacklist");
  </Binding>
  <Binding name="BAGSYNCCURRENCY" header="BAGSYNC2" category="ADDONS">
    BagSync_ShowWindow("Currency");
  </Binding>
  <Binding name="BAGSYNCGOLD" header="BAGSYNC3" category="ADDONS">
    BagSync_ShowWindow("Gold");
  </Binding>
  <Binding name="BAGSYNCPROFESSIONS" header="BAGSYNC4" category="ADDONS">
    BagSync_ShowWindow("Professions");
  </Binding>
  <Binding name="BAGSYNCPROFILES" header="BAGSYNC5" category="ADDONS">
    BagSync_ShowWindow("Profiles");
  </Binding>
   <Binding name="BAGSYNCSEARCH" header="BAGSYNC6" category="ADDONS">
    BagSync_ShowWindow("Search");
  </Binding>
</Bindings>

**Comment by cremor** [comment] 2018-07-21 11:51
Better just remove all `header="BAGSYNC"` except the first one. Then they'll still all use the same header.

**Comment by DennisJohnsen** [comment] 2018-07-23 11:22
I am also having this issue. Can you make an official update to your addon to fix this for 8.0.1?

```
Message: Binding header BAGSYNC is defined more than once in Interface\AddOns\BagSync\Bindings.xml
Time: Mon Jul 23 13:20:39 2018
Count: 1
```

**Comment by Xruptor** [comment] 2018-07-23 20:36
I'm currently updating all the addons I have.  I'm looking into current bugs and this one seems to be caused by changes to how bindings are done now.

**Comment by Xruptor** [comment] 2018-07-23 20:40
I've fixed this in the current commit push.  Once I address all the bugs it should be fixed in the released version soon.

**Closed** 2018-07-23 20:40 UTC
