### ISSUE TITLE
When trying to use Might of Dalaran I get this error message about 132 times

### ISSUE THREAD

**Issue by Tannx1980** [Xruptor/BagSync#59] opened 2017-02-16 13:27 UTC
Date: 2017-02-16 06:22:12
ID: 5
Error occured in: AddOn: BagSync
Count: 3
Message: Note: AddOn BagSync attempted to call a protected function (<unnamed>:Hide()) during combat lockdown.
Debug:
   [C]: Hide()
   ..\FrameXML\WorldMapActionButton.lua:58: Clear()
   ..\FrameXML\WorldMapActionButton.lua:67: Refresh()
   ..\FrameXML\WorldMapActionButton.lua:19: SetMapAreaID()
   ..\FrameXML\WorldMapFrame.lua:1230: WorldMapFrame_Update()
   ..\FrameXML\WorldMapFrame.lua:2809: WorldMapFrame_UpdateMap()
   ..\FrameXML\WorldMapFrame.lua:436:
      ..\FrameXML\WorldMapFrame.lua:422
   [C]: ?
   [C]: SetMapToCurrentZone()
   ..\FrameXML\WorldMapFrame.lua:370:
      ..\FrameXML\WorldMapFrame.lua:349
   [C]: Show()
   ..\FrameXML\UIParent.lua:2327: SetUIPanel()
   ..\FrameXML\UIParent.lua:2166: ShowUIPanel()
   ..\FrameXML\UIParent.lua:2086:
      ..\FrameXML\UIParent.lua:2082
   [C]: SetAttribute()
   ..\FrameXML\UIParent.lua:2868: ShowUIPanel()
   ..\FrameXML\UIParent.lua:2852: ToggleFrame()
   ..\FrameXML\WorldMapFrame.lua:261:
      ..\FrameXML\WorldMapFrame.lua:233
   [C]: ToggleWorldMap()
   [string "TOGGLEWORLDMAP"]:1:
      [string "TOGGLEWORLDMAP"]:1
Locals:
None
AddOns:
  Swatter, v7.3a.5701 (TasmanianThylacine)
  AucAdvanced, v7.3a.5701 (TasmanianThylacine)
  AucFilterBasic, v7.3a.5701 (TasmanianThylacine)
  AucFilterOutlier, v7.3a.5701.5459(7.3a/embedded)
  AucMatchUndercut, v7.3a.5701.5585(7.3a/embedded)
  AucScanData, v7.3a.5701 (TasmanianThylacine)
  AucStatHistogram, v7.3a.5701 (TasmanianThylacine)
  AucStatiLevel, v7.3a.5701 (TasmanianThylacine)
  AucStatPurchased, v7.3a.5701 (TasmanianThylacine)
  AucStatSales, v7.3a.5701.5598(7.3a/embedded)
  AucStatSimple, v7.3a.5701 (TasmanianThylacine)
  AucStatStdDev, v7.3a.5701 (TasmanianThylacine)
  AucStatWOWEcon, v7.3a.5701.5613(7.3a/embedded)
  AucUtilAHWindowControl, v7.3a.5701.5575(7.3a/embedded)
  AucUtilAppraiser, v7.3a.5701.5666(7.3a/embedded)
  AucUtilAskPrice, v7.3a.5701.5599(7.3a/embedded)
  AucUtilAutoMagic, v7.3a.5701.5686(7.3a/embedded)
  AucUtilCompactUI, v7.3a.5701.5694(7.3a/embedded)
  AucUtilEasyBuyout, v7.3a.5701.5576(7.3a/embedded)
  AucUtilFixAH, v7.3a.5701 (TasmanianThylacine)
  AucUtilItemSuggest, v7.3a.5701.5651(7.3a/embedded)
  AucUtilPriceLevel, v7.3a.5701.5633(7.3a/embedded)
  AucUtilScanButton, v7.3a.5701.5631(7.3a/embedded)
  AucUtilScanFinish, v7.3a.5701.5588(7.3a/embedded)
  AucUtilScanProgress, v7.3a.5701.4979(7.3a/embedded)
  AucUtilScanStart, v7.3a.5701.5347(7.3a/embedded)
  AucUtilSearchUI, v7.3a.5701.5672(7.3a/embedded)
  AucUtilSimpleAuction, v7.3a.5701.5654(7.3a/embedded)
  AucUtilVendMarkup, v7.3a.5701.4828(7.3a/embedded)
  Babylonian, v5.1.DEV.332(/embedded)
  BagSync, v10.9
  BattlePetBreedID, vr134
  BeanCounter, v7.3a.5701 (TasmanianThylacine)
  BloodTrader, v2.1.1
  Configator, v5.1.DEV.406(/embedded)
  DBMCore, v7.1.13
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DebugLib, v5.1.DEV.337(/embedded)
  Enchantrix, v7.3a.5701 (TasmanianThylacine)
  EnchantrixBarker, v7.3a.5701 (TasmanianThylacine)
  HandyNotes, vv1.4.11
  HandyNotesDraenorTreasures, v1.20a
  HandyNotesLegionTreasures, v1
  HandyNotesSuramarLeylines, v1
  HandyNotesSuramarTelemancy, v1
  HealBot, v7.1.0.1
  HealBotTips, v7.1.0.1
  Informant, v7.3a.5701 (TasmanianThylacine)
  LibExtraTip, v5.12.DEV.423(/embedded)
  LiteBag, v7.1.5
  Skada, v1.6.5
  SlideBar, v7.3a.5701 (TasmanianThylacine)
  Stubby, v7.3a.5701 (TasmanianThylacine)
  TipHelper, v5.12.DEV.405(/embedded)
  TomTom, vv70100-1.0.0
  WorldQuestTracker, v
  BlizRuntimeLib_enUS v7.1.5.70100 <none>
  (ck=951)

**Comment by Xruptor** [comment] 2017-02-21 15:06
It appears to be an issue with you entering combat and BagSync trying to do something.  The only problem is that this error is so generic it's hard for me to pinpoint where the issue is.  The only time Hide is called is for the tooltip info and that's really only when you hover over something.  The only exception to this is if you have the BagSync minimap button displayed.  Other then that hide is only called when you close any of the BagSync module windows, like search, professions, etc...   So unless you are opening and closing BagSync windows or constantly hovering items during combat, i'm not entirely sure how this is being triggered.

Can you try to replicate it exactly?  Try not having any BagSync windows opened and then one at a time experiment with opening and closing them and or hovering over item tooltips during combat to see if you can replicate this problem.

**Closed** 2018-07-23 20:31 UTC
