### ISSUE TITLE
Warbank on tooltip not visible until visited

### ISSUE THREAD

**Issue by Kikaroo** [Xruptor/BagSync#363] opened 2024-08-17 23:26 UTC
So I noticed today that items in the Warbank are not visible on the tooltip unless I visit the Warbank on that toon during that session. Once I log over to another character or reload the current character, the Warbank info vanishes again. Everything else (guild banks, etc) seem to be working okay.

**Comment by Sluimerstand** [comment] 2024-08-18 10:57
For my part, reloading does seem to retain the info, but logging out/in definitely has this info be absent until the Warbank is visited.

**Comment by Xruptor** [comment] 2024-08-18 11:16
I'll try to see if I can reproduce this issue.  I have only access to the PTR as I don't have a subscription.  So issues like these are sometimes difficult for me to debug.  I may require you guys to test for me.

**Comment by Xruptor** [comment] 2024-08-18 13:32
It's possible that Blizzard is sending events for the Warband bank even when you aren't at one.  Which means the bags would return zero or empty in that case.  If that happens then the bags would be emptied out and you wouldn't see anything until next session.  I'll take a look and see if something like that is happening.  I wouldn't be surprised if they did that, a lot of their coding is super sloppy and I'm constantly having to band-aid fix everything.

**Comment by Xruptor** [comment] 2024-08-18 14:43
@Kikaroo and @Sluimerstand please try this version and let me know if it works.  Make sure to move around items in the Warband in and out of your bags and switch characters.  Try logging in and out and even exiting out of the WOW client completely.

[BagSync.zip](https://github.com/user-attachments/files/16649207/BagSync.zip)

**Comment by Arrothben** [comment] 2024-08-18 15:42
Also having the issue but the zip file fixed it for me.

**Comment by Sluimerstand** [comment] 2024-08-18 17:16
> Kikaroo and Sluimerstand please try this version and let me know if it works.

@Xruptor Tested with logging around characters and closing the game entirely, this seems to be retaining the information properly now. :)

**Closed** 2024-08-18 19:30 UTC
Labels: 🐛 bug, 🔍 requires investigation, ⏱ awaiting user response

**Comment by Xruptor** [comment] 2024-08-18 19:35
Thanks for testing folks :)  Pushing to live.
