### ISSUE TITLE
same guild across multiple connected servers

### ISSUE THREAD

**Issue by JimGiordano2** [Xruptor/BagSync#285] opened 2023-03-25 01:47 UTC

**Comment by Xruptor** [comment] 2023-03-25 01:53
You wrote the entire problem as the title for the ticket.  Here is your original post.

> **same guild across multiple connected servers**-  I have many alts across three connected servers, and they all belong to my private guild.  Bagsync treats them as different guilds, showing the current server just by the server name, and also a line for the quild on the other server, and adds both into the total count of items found.  I tried every setting under the config window, but no luck.  Is there a simple fix for this?

**Comment by Xruptor** [comment] 2023-03-25 01:54
Please stop editing it.

**Comment by JimGiordano2** [comment] 2023-03-25 01:54
sorry, first time using this system.   easy to tell a Noob.

**Comment by Xruptor** [comment] 2023-03-25 01:55
No worries, you kept putting the entire description in the title line.

**Comment by Xruptor** [comment] 2023-03-25 01:56
I will look into the issue when I have a chance.  If you can provide some pictures and such of your issue as well, that helps me a lot. You can copy and paste the pictures here in the commands or click the "Attach files" line at the bottom of the comment box.

**Comment by Xruptor** [comment] 2023-03-25 02:02
Also please do the following:

1. Type `/bgs debug`
2. Check "Enable Debug"
3. Make sure only "DEBUG" is selected.
4. Press "Clear"
5. Press "Iterate Units"
6. Press "Export"
7. Select all the text and copy Ctrl+C and paste it here Ctrl+V, or you can take a screenshot up to you.

**Comment by JimGiordano2** [comment] 2023-03-25 02:04
Here's a little screen shot showing the results
![bagsyncproblem](https://user-images.githubusercontent.com/39205588/227680334-3e8026ef-8880-4788-970f-b68ba8875f07.png)

**Comment by JimGiordano2** [comment] 2023-03-25 02:05
Yes, the guild name is  "ii"

**Comment by JimGiordano2** [comment] 2023-03-25 02:09
[19:07:50]: [Unit]: GetPlayerInfo, Ikî, Thorium Brotherhood, Alliance, MAGE, Worgen, ii©
[19:07:50]: [Data]: IterateUnits, nil, nil
[19:08:07]: [Unit]: GetPlayerInfo, Ikî, Thorium Brotherhood, Alliance, MAGE, Worgen, ii©
[19:08:07]: [Tooltip]: TallyUnits, CacheUsed, [Potion of Prolonged Power]
[19:08:07]: [Data]: GetPlayerObj, Ikî, Thorium Brotherhood, true
[19:08:07]: [Tooltip]: ColorizeUnit, |A:raceicon-worgen-male:13:13:0:0|a  Ikî, Thorium Brotherhood, true, false, Thorium Brotherhood
[19:08:07]: [Data]: GetPlayerGuild, ii©, true
[19:08:07]: [Tooltip]: ColorizeUnit,  ii, Thorium Brotherhood, true, false, Thorium Brotherhood
[19:08:07]: [Tooltip]: TallyUnits, 142117, 142117, OnTooltipSetItem, nil, 988, WL-OFF

**Comment by Xruptor** [comment] 2023-03-25 02:17
> Also please do the following:
> 
> 1. Type `/bgs debug`
> 2. Check "Enable Debug"
> 3. Make sure only "DEBUG" is selected.
> 4. Press "Clear"
> 5. Press "Iterate Units"
> 6. Press "Export"
> 7. Select all the text and copy Ctrl+C and paste it here Ctrl+V, or you can take a screenshot up to you.

:) please follow these steps one at a time.

**Comment by Xruptor** [comment] 2023-03-25 02:18
![image](https://user-images.githubusercontent.com/202515/227681665-0d124c5d-9935-4f89-9be2-9758a2ed0d38.png)

**Comment by JimGiordano2** [comment] 2023-03-25 02:29
Here it is from a different character on another server-
[19:26:24]: [IterateUnits]: UnitInfo-1, Yopa, Farstriders
[19:26:24]: [IterateUnits]: UnitInfo-2, MAGE, Pandaren, 3, Alliance
[19:26:24]: [IterateUnits]: UnitInfo-3, ii©, ThoriumBrotherhood
[19:26:24]: [IterateUnits]: RealmKey, Farstriders;Silver Hand;Thorium Brotherhood
[19:26:24]: [IterateUnits]: RealmKey_RWS, SilverHand;ThoriumBrotherhood;Farstriders
[19:26:24]: [IterateUnits]: player, Tug, Silver Hand, true, ii©, ThoriumBrotherhood, Farstriders;Silver Hand;Thorium Brotherhood, SilverHand;ThoriumBrotherhood;Farstriders
[19:26:24]: [IterateUnits]: player, Fip, Silver Hand, true, ii©, ThoriumBrotherhood, Farstriders;Silver Hand;Thorium Brotherhood, SilverHand;ThoriumBrotherhood;Farstriders
[19:26:24]: [IterateUnits]: guild, ii©, Thorium Brotherhood, true, false, Farstriders;Silver Hand;Thorium Brotherhood, SilverHand;ThoriumBrotherhood;Farstriders
[19:26:24]: [IterateUnits]: player, Ikî, Thorium Brotherhood, true, ii©, Thorium Brotherhood, Farstriders;Silver Hand;Thorium Brotherhood, SilverHand;ThoriumBrotherhood;Farstriders
[19:26:24]: [IterateUnits]: player, Yopa, Farstriders, true, ii©, ThoriumBrotherhood, Farstriders;Silver Hand;Thorium Brotherhood, SilverHand;ThoriumBrotherhood;Farstriders
[19:26:24]: [IterateUnits]: guild, ii©, ThoriumBrotherhood, true, false, Farstriders;Silver Hand;Thorium Brotherhood, SilverHand;ThoriumBrotherhood;Farstriders
![bagsync3](https://user-images.githubusercontent.com/39205588/227682107-b4141635-866c-4045-a500-37da626d238c.png)

**Comment by JimGiordano2** [comment] 2023-03-25 02:37
And from a character on the third server-
![bagsync3](https://user-images.githubusercontent.com/39205588/227682419-9aa643c9-699e-4598-b1b7-eea58db70f5b.png)

**Comment by JimGiordano2** [comment] 2023-03-25 02:41
Note that the count is different for the two lines for the guild shown.  The count will be corrected when I use a character on thorium brotherhood and look at the guild bank.  It's wrong now, because I withdrew one item for each for Yopa  and Tug since the last time I was on thorium.

**Comment by Xruptor** [comment] 2023-03-25 11:56
Thank you so much for the info!  😃 🎉 It helps me a lot to try to figure out the issue.  I'll review what you posted and see if I can trace the issue and slap the bug lol.  I may ask for some more information or give you test versions of BagSync to try.

**Comment by Xruptor** [comment] 2023-03-25 12:26
Okay there may be a possibility that Blizzard is returning the wrong server name for connected guilds.  You'll notice that there are two listed but actually they are different.  One has a space the other does not.  "Thorium Brotherhood" is not the same as "ThoriumBrotherhood" that is why it's showing twice.  The two actually don't match because of the extra space.  It's possible that Blizzard is sending both names and that is where the problem is.  I need to do checks for this.

Can you please upload here your BagSync.lua found under your WOW installation.  You may need to zip it up.  You can find it at the following location.
`WOW INSTALL Directory\_retail_\WTF\Account\<your account name>\SavedVariables\BagSync.lua`

To attach a file click on "Attach files by dragging and dropping" at the bottom of the comment box.

**Comment by Xruptor** [comment] 2023-03-25 13:28
In addition to my request above, I need you to login to some of your characters both on the same realm as your guild and those on connected realms.  I need various checks to ensure this is the problem.  So on each toon type the following in your chatbox exactly (I suggest you copy and paste it) and show me the results.

`/script print("DEBUG", " || ", _G.GetRealmName(), " || ", select(4, _G.GetGuildInfo("player")))`

**Comment by JimGiordano2** [comment] 2023-03-25 13:31
[BagSync.zip](https://github.com/Xruptor/BagSync/files/11068998/BagSync.zip)

Thank you for your quick response and actions.   I used to use the addon BankItems, but I couldn't figure out how to fix it with the latest changes, so BagSync is a real game saver for me :)

**Comment by Xruptor** [comment] 2023-03-25 13:40
No worries I want to make sure it's working correctly for you.  If it's a bug on Blizzards end I need to work around it.  Let me know the results of the `/script` above as well 😄

**Comment by JimGiordano2** [comment] 2023-03-25 14:17
And here's the results from the script-

DEBUG  ||  Thorium Brotherhood  ||  nil
DEBUG  ||  Thorium Brotherhood  ||  nil

DEBUG  ||  Silver Hand  ||  ThoriumBrotherhood

DEBUG  ||  Farstriders  ||  ThoriumBrotherhood

**Comment by Xruptor** [comment] 2023-03-25 14:21
YEP! It's what I suspected.  If you notice on servers that aren't the same as the guild it's returning the wrong guild name.  This is Blizzards fault.  I'm going to have to make fixes for their mess.

**Comment by JimGiordano2** [comment] 2023-03-25 14:30
Thanks!

**Comment by Xruptor** [comment] 2023-03-25 15:36
Okay so lets try an edited version of BagSync to fix this issue.

[BagSync.zip](https://github.com/Xruptor/BagSync/files/11069281/BagSync.zip)

Okay try that version of BagSync.  If you don't know how to install addons manually, just extract that to following directory.  You may want to delete the BagSync that's already there or you can overwrite it, up to you.
`WOW INSTALL Directory\_retail_\Interace\Addons\`

Once you installed **PLEASE** follow these steps.

1) Login to each and every one of your characters on every realm and check the guild bank.
2) Once the above is done, verify the guild is only showing up once now, no matter what character you login as.
3) Do the following command,  `/bgs fixdb`
4) Finally upload your BagSync,lua file again here to verify everything is correct in the database.

**Comment by JimGiordano2** [comment] 2023-03-25 16:16
Looks good so far :)
[BagSync.zip](https://github.com/Xruptor/BagSync/files/11069376/BagSync.zip)

**Comment by JimGiordano2** [comment] 2023-03-25 17:13
sorry, just noticed I forgot to fixdb.  will do that now.

**Comment by JimGiordano2** [comment] 2023-03-25 17:16
[BagSync.zip](https://github.com/Xruptor/BagSync/files/11069538/BagSync.zip)

**Comment by Xruptor** [comment] 2023-03-25 17:30
> sorry, just noticed I forgot to fixdb. will do that now.

Okay it looks like the database is cleaned up now on your end.  I also verified it on my end as well.  So this issue was fixed.  I had to perform some checks to make sure the server name Blizzard is returning is one we already knew or had stored.  It's a mistake on their part to send back the "Normalized" realm name.  Which is a realm with no spaces or hyphens.  It causes a whole heap of issues for addon authors.  I'll finalize the changes and push a live update.  Thanks for your patience and helping me out to get this resolved.

**Comment by JimGiordano2** [comment] 2023-03-25 17:43
And thank you for your excellent addon and quick response and patience :)

Please delete all this stuff,  many of my posts are just embarrassing.

**Comment by Xruptor** [comment] 2023-03-25 19:13
> And thank you for your excellent addon and quick response and patience :)
> 
> Please delete all this stuff, many of my posts are just embarrassing.

Of course! Glad it worked out and bug reports like yours helps me out in the end for others whom may have the same issue.  Don't worry about this ticket, I will close it once I push the changes.

**Closed** 2023-03-25 19:20 UTC
Labels: requires investigation

**Comment by Xruptor** [comment] 2023-03-25 19:25
I pushed the changes to V19.5 enjoy.
