### ISSUE TITLE
BagSync + ElvUI

### ISSUE THREAD

**Issue by leemitchell25** [Xruptor/BagSync#125] opened 2020-10-17 18:56 UTC
Hi there,

Love your addon but I'm running into an issue when running it with ElvUI.

When logging in, or after a /reload, a white X appears on screen that needs to be clicked 6 times in order to clear it. While the X is on-screen any mouse commands in the center area of the screen do not work.

My assumption is BagSync is loading a dialog (or 6 dialogs) that are then not closing due to a error with ElvUI. (I'm only running BagSync and ElvUI while testing this.)

Here are the related LUA Errors:

(LOG 1/6)

Message: Interface\AddOns\ElvUI\Core\Toolkit.lua:135: attempt to call method 'SetBackdrop' (a nil value)
Time: Sat Oct 17 14:50:29 2020
Count: 1
Stack: Interface\AddOns\ElvUI\Core\Toolkit.lua:135: attempt to call method 'SetBackdrop' (a nil value)
[string "@Interface\AddOns\ElvUI\Core\Toolkit.lua"]:135: in function `SetTemplate'
[string "@Interface\AddOns\ElvUI\Modules\Skins\Addons\Ace3.lua"]:392: in function `Ace3_RegisterAsContainer'
[string "@Interface\AddOns\ElvUI\Modules\Skins\Addons\Ace3.lua"]:485: in function `RegisterAsContainer'
[string "@Interface\AddOns\BagSync\libs\AceGUI-3.0\widgets\AceGUIContainer-Window.lua"]:331: in function `?'
[string "@Interface\AddOns\BagSync\libs\AceGUI-3.0\AceGUI-3.0.lua"]:108: in function <...erface\AddOns\BagSync\libs\AceGUI-3.0\AceGUI-3.0.lua:97>
[string "@Interface\AddOns\BagSync\libs\AceGUI-3.0\AceGUI-3.0.lua"]:146: in function `Create'
[string "@Interface\AddOns\BagSync\modules\search.lua"]:28: in function <Interface\AddOns\BagSync\modules\search.lua:25>
[string "=[C]"]: ?
[string "@Interface\AddOns\BagSync\libs\AceAddon-3.0\AceAddon-3.0.lua"]:70: in function <...ce\AddOns\BagSync\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Interface\AddOns\BagSync\libs\AceAddon-3.0\AceAddon-3.0.lua"]:527: in function `EnableAddon'
[string "@Interface\AddOns\BagSync\libs\AceAddon-3.0\AceAddon-3.0.lua"]:540: in function `EnableAddon'
[string "@Interface\AddOns\BagSync\libs\AceAddon-3.0\AceAddon-3.0.lua"]:630: in function <...ce\AddOns\BagSync\libs\AceAddon-3.0\AceAddon-3.0.lua:615>

Locals: <none>

(LOG 2/6)

Message: Interface\AddOns\ElvUI\Core\Toolkit.lua:135: attempt to call method 'SetBackdrop' (a nil value)
Time: Sat Oct 17 14:50:29 2020
Count: 1
Stack: Interface\AddOns\ElvUI\Core\Toolkit.lua:135: attempt to call method 'SetBackdrop' (a nil value)
[string "@Interface\AddOns\ElvUI\Core\Toolkit.lua"]:135: in function `SetTemplate'
[string "@Interface\AddOns\ElvUI\Modules\Skins\Addons\Ace3.lua"]:392: in function `Ace3_RegisterAsContainer'
[string "@Interface\AddOns\ElvUI\Modules\Skins\Addons\Ace3.lua"]:485: in function `RegisterAsContainer'
[string "@Interface\AddOns\BagSync\libs\AceGUI-3.0\widgets\AceGUIContainer-Window.lua"]:331: in function `?'
[string "@Interface\AddOns\BagSync\libs\AceGUI-3.0\AceGUI-3.0.lua"]:108: in function <...erface\AddOns\BagSync\libs\AceGUI-3.0\AceGUI-3.0.lua:97>
[string "@Interface\AddOns\BagSync\libs\AceGUI-3.0\AceGUI-3.0.lua"]:146: in function `Create'
[string "@Interface\AddOns\BagSync\modules\currency.lua"]:27: in function <Interface\AddOns\BagSync\modules\currency.lua:24>
[string "=[C]"]: ?
[string "@Interface\AddOns\BagSync\libs\AceAddon-3.0\AceAddon-3.0.lua"]:70: in function <...ce\AddOns\BagSync\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Interface\AddOns\BagSync\libs\AceAddon-3.0\AceAddon-3.0.lua"]:527: in function `EnableAddon'
[string "@Interface\AddOns\BagSync\libs\AceAddon-3.0\AceAddon-3.0.lua"]:540: in function `EnableAddon'
[string "@Interface\AddOns\BagSync\libs\AceAddon-3.0\AceAddon-3.0.lua"]:630: in function <...ce\AddOns\BagSync\libs\AceAddon-3.0\AceAddon-3.0.lua:615>

Locals: <none>

(LOG 3/6)

Message: Interface\AddOns\ElvUI\Core\Toolkit.lua:135: attempt to call method 'SetBackdrop' (a nil value)
Time: Sat Oct 17 14:50:29 2020
Count: 1
Stack: Interface\AddOns\ElvUI\Core\Toolkit.lua:135: attempt to call method 'SetBackdrop' (a nil value)
[string "@Interface\AddOns\ElvUI\Core\Toolkit.lua"]:135: in function `SetTemplate'
[string "@Interface\AddOns\ElvUI\Modules\Skins\Addons\Ace3.lua"]:392: in function `Ace3_RegisterAsContainer'
[string "@Interface\AddOns\ElvUI\Modules\Skins\Addons\Ace3.lua"]:485: in function `RegisterAsContainer'
[string "@Interface\AddOns\BagSync\libs\AceGUI-3.0\widgets\AceGUIContainer-Window.lua"]:331: in function `?'
[string "@Interface\AddOns\BagSync\libs\AceGUI-3.0\AceGUI-3.0.lua"]:108: in function <...erface\AddOns\BagSync\libs\AceGUI-3.0\AceGUI-3.0.lua:97>
[string "@Interface\AddOns\BagSync\libs\AceGUI-3.0\AceGUI-3.0.lua"]:146: in function `Create'
[string "@Interface\AddOns\BagSync\modules\currency.lua"]:27: in function <Interface\AddOns\BagSync\modules\currency.lua:24>
[string "=[C]"]: ?
[string "@Interface\AddOns\BagSync\libs\AceAddon-3.0\AceAddon-3.0.lua"]:70: in function <...ce\AddOns\BagSync\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Interface\AddOns\BagSync\libs\AceAddon-3.0\AceAddon-3.0.lua"]:527: in function `EnableAddon'
[string "@Interface\AddOns\BagSync\libs\AceAddon-3.0\AceAddon-3.0.lua"]:540: in function `EnableAddon'
[string "@Interface\AddOns\BagSync\libs\AceAddon-3.0\AceAddon-3.0.lua"]:630: in function <...ce\AddOns\BagSync\libs\AceAddon-3.0\AceAddon-3.0.lua:615>

Locals: <none>

(LOG 4/6)

Message: Interface\AddOns\ElvUI\Core\Toolkit.lua:135: attempt to call method 'SetBackdrop' (a nil value)
Time: Sat Oct 17 14:50:29 2020
Count: 1
Stack: Interface\AddOns\ElvUI\Core\Toolkit.lua:135: attempt to call method 'SetBackdrop' (a nil value)
[string "@Interface\AddOns\ElvUI\Core\Toolkit.lua"]:135: in function `SetTemplate'
[string "@Interface\AddOns\ElvUI\Modules\Skins\Addons\Ace3.lua"]:392: in function `Ace3_RegisterAsContainer'
[string "@Interface\AddOns\ElvUI\Modules\Skins\Addons\Ace3.lua"]:485: in function `RegisterAsContainer'
[string "@Interface\AddOns\BagSync\libs\AceGUI-3.0\widgets\AceGUIContainer-Window.lua"]:331: in function `?'
[string "@Interface\AddOns\BagSync\libs\AceGUI-3.0\AceGUI-3.0.lua"]:108: in function <...erface\AddOns\BagSync\libs\AceGUI-3.0\AceGUI-3.0.lua:97>
[string "@Interface\AddOns\BagSync\libs\AceGUI-3.0\AceGUI-3.0.lua"]:146: in function `Create'
[string "@Interface\AddOns\BagSync\modules\currency.lua"]:27: in function <Interface\AddOns\BagSync\modules\currency.lua:24>
[string "=[C]"]: ?
[string "@Interface\AddOns\BagSync\libs\AceAddon-3.0\AceAddon-3.0.lua"]:70: in function <...ce\AddOns\BagSync\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Interface\AddOns\BagSync\libs\AceAddon-3.0\AceAddon-3.0.lua"]:527: in function `EnableAddon'
[string "@Interface\AddOns\BagSync\libs\AceAddon-3.0\AceAddon-3.0.lua"]:540: in function `EnableAddon'
[string "@Interface\AddOns\BagSync\libs\AceAddon-3.0\AceAddon-3.0.lua"]:630: in function <...ce\AddOns\BagSync\libs\AceAddon-3.0\AceAddon-3.0.lua:615>

Locals: <none>

(LOG 5/6)

Message: Interface\AddOns\ElvUI\Core\Toolkit.lua:135: attempt to call method 'SetBackdrop' (a nil value)
Time: Sat Oct 17 14:50:29 2020
Count: 1
Stack: Interface\AddOns\ElvUI\Core\Toolkit.lua:135: attempt to call method 'SetBackdrop' (a nil value)
[string "@Interface\AddOns\ElvUI\Core\Toolkit.lua"]:135: in function `SetTemplate'
[string "@Interface\AddOns\ElvUI\Modules\Skins\Addons\Ace3.lua"]:392: in function `Ace3_RegisterAsContainer'
[string "@Interface\AddOns\ElvUI\Modules\Skins\Addons\Ace3.lua"]:485: in function `RegisterAsContainer'
[string "@Interface\AddOns\BagSync\libs\AceGUI-3.0\widgets\AceGUIContainer-Window.lua"]:331: in function `?'
[string "@Interface\AddOns\BagSync\libs\AceGUI-3.0\AceGUI-3.0.lua"]:108: in function <...erface\AddOns\BagSync\libs\AceGUI-3.0\AceGUI-3.0.lua:97>
[string "@Interface\AddOns\BagSync\libs\AceGUI-3.0\AceGUI-3.0.lua"]:146: in function `Create'
[string "@Interface\AddOns\BagSync\modules\blacklist.lua"]:27: in function <Interface\AddOns\BagSync\modules\blacklist.lua:24>
[string "=[C]"]: ?
[string "@Interface\AddOns\BagSync\libs\AceAddon-3.0\AceAddon-3.0.lua"]:70: in function <...ce\AddOns\BagSync\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Interface\AddOns\BagSync\libs\AceAddon-3.0\AceAddon-3.0.lua"]:527: in function `EnableAddon'
[string "@Interface\AddOns\BagSync\libs\AceAddon-3.0\AceAddon-3.0.lua"]:540: in function `EnableAddon'
[string "@Interface\AddOns\BagSync\libs\AceAddon-3.0\AceAddon-3.0.lua"]:630: in function <...ce\AddOns\BagSync\libs\AceAddon-3.0\AceAddon-3.0.lua:615>

Locals: <none>

(LOG 6/6)

Message: Interface\AddOns\ElvUI\Core\Toolkit.lua:135: attempt to call method 'SetBackdrop' (a nil value)
Time: Sat Oct 17 14:50:29 2020
Count: 1
Stack: Interface\AddOns\ElvUI\Core\Toolkit.lua:135: attempt to call method 'SetBackdrop' (a nil value)
[string "@Interface\AddOns\ElvUI\Core\Toolkit.lua"]:135: in function `SetTemplate'
[string "@Interface\AddOns\ElvUI\Modules\Skins\Addons\Ace3.lua"]:392: in function `Ace3_RegisterAsContainer'
[string "@Interface\AddOns\ElvUI\Modules\Skins\Addons\Ace3.lua"]:485: in function `RegisterAsContainer'
[string "@Interface\AddOns\BagSync\libs\AceGUI-3.0\widgets\AceGUIContainer-Window.lua"]:331: in function `?'
[string "@Interface\AddOns\BagSync\libs\AceGUI-3.0\AceGUI-3.0.lua"]:108: in function <...erface\AddOns\BagSync\libs\AceGUI-3.0\AceGUI-3.0.lua:97>
[string "@Interface\AddOns\BagSync\libs\AceGUI-3.0\AceGUI-3.0.lua"]:146: in function `Create'
[string "@Interface\AddOns\BagSync\modules\blacklist.lua"]:27: in function <Interface\AddOns\BagSync\modules\blacklist.lua:24>
[string "=[C]"]: ?
[string "@Interface\AddOns\BagSync\libs\AceAddon-3.0\AceAddon-3.0.lua"]:70: in function <...ce\AddOns\BagSync\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Interface\AddOns\BagSync\libs\AceAddon-3.0\AceAddon-3.0.lua"]:527: in function `EnableAddon'
[string "@Interface\AddOns\BagSync\libs\AceAddon-3.0\AceAddon-3.0.lua"]:540: in function `EnableAddon'
[string "@Interface\AddOns\BagSync\libs\AceAddon-3.0\AceAddon-3.0.lua"]:630: in function <...ce\AddOns\BagSync\libs\AceAddon-3.0\AceAddon-3.0.lua:615>

Locals: <none>

**Comment by aastarius** [comment] 2020-10-17 19:51
Well that just saved me a whole lot of typing.

Can confirm I am having the exact same issue!

**Comment by Xruptor** [comment] 2020-10-17 20:26
This is not a bug with Bagsync. It was recently fixed on ElvUi. Please update your ElvUI installation.

**Closed by Xruptor** 2020-10-17 20:26 UTC
Labels: Not a Bug

**Comment by leemitchell25** [comment] 2020-10-17 20:59
Confirmed fixed. Thank you!! :D
